# railway.toml

[build]
builder = "NIXPACKS"

[build.args]
JAVA_VERSION = "8"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/*.jar"

[variables]
JAVA_HOME = "/usr/lib/jvm/java-8-openjdk"
